name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.3

    - name: Use Node.js v20.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: v20.x

    - name: Build
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
        token: ${{ github.token }}
