name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: v20.x

    - name: Build
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: dist/

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
